# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170722_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
