# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 07:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per month', max_digits=4)),
                ('price_text', models.CharField(help_text='$xxx/month or free or custom', max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(help_text='Data Plan Features')),
                ('highlights', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), help_text='Data Plan Features in text', size=16)),
            ],
        ),
    ]
