# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataplan',
            name='price_text',
        ),
        migrations.AddField(
            model_name='dataplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dataplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per month. Warning: you cannot modify the price field after (stripe)!', max_digits=4),
        ),
    ]
