# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20170521_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataplan',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='dataplan',
            name='order',
            field=models.SmallIntegerField(default=0, help_text='Smaller at the first of list'),
        ),
    ]
